src/social website/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('stamps.views',
    url(r'^display/$', 'display'),
    url(r'^stamps/$', 'stamps_list'),
    url(r'^upload/$', 'upload'),
    url(r'^signup/$', 'signup'),
    url(r'^login/$', 'user_login'),
    url(r'^home/$', 'user_home'),
    url(r'^finder/$', 'match_finder'),
    url(r'^edit/$', 'user_edit'),
    url(r'^friends/$', 'user_friends'),
    url(r'^collection/$', 'user_collection'),
    url(r'^interest/$', 'trade_interest'),
    url(r'^user/$', 'user_page'),
    url(r'^transaction_review/$', 'transaction_review'),
    url(r'^transaction/$', 'transaction_display'),
    url(r'^messages/$', 'get_messages'),
    url(r'^mailbox/$', 'all_messages'),

    
#redirection url
    url(r'^logout/$', 'user_logout'),
    url(r'^interested/$', 'interested'),
    url(r'^accepted/$', 'interest_confirmed'),
    url(r'^naccepted/$', 'interest_canceled'),
    url(r'^done/$', 'transaction_confirmed'),
    url(r'^ndone/$', 'transaction_canceled'),
    url(r'^friendreq/$', 'request_confirmed'),
    url(r'^nfriendreq/$', 'request_canceled'),
    url(r'^delete/$', 'delete_collection'),
)

src/social website/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.core.validators import MaxLengthValidator
from stamps.multiselect import MultiSelectField

CATALOG_CHOICES = (
    ('MI','Michel'),
    ('SC','Scott'),
    ('ST','Stanley Gibbons'),
    ('YV','Yvert et Tellier'),
    ('WA', 'WADP Numbering System'),
    ('SN', 'Stamp Number'),
    ('NO', 'None of the above'),
)

PAPER_CHOICES = (
    ('WO','Wove'),
    ('LA','Laid'),
    ('BA','Batonne'),
    ('PE','Pelure'),
    ('SI','Silk'),
    ('GR','Granite'),
    ('NO', 'None of the above'),
)

METHOD_CHOICES = (
    (0,'Engraving'),
    (1,'Typography'),
    (2,'Lithography'),
    (3,'Offset'),
    (4,'Recess'),
    (5, 'Letterset'),
    (6, 'Laserprint'),
    (7, 'Mezzotint'),
    (8, 'Photogravure'),
    (9, 'Collotype'),
    (10, 'Embossed'),
    (50, 'Other'),
)

FRIENDSHIP_CHOICES = (
    ('AC', 'Acquaintance'),
    ('FR', 'Friend'),
    ('PE', 'Pending'),
)

QUALITY_CHOICES = (
    ('MI', 'Mint'),
    ('US', 'Used'),
)
STATE_CHOICES = (
    ('PE', 'Pending'),
    ('AC', 'Accepted'),
    ('DO', 'Done'),
    ('RE', 'Reviewed'),
)
TRUST_CHOICES = (
    ('SC', 'Script addition'),
    ('US', 'User addition'),
)
# Create your models here.
class Stamp(models.Model):
    issue_country = models.CharField(max_length=65)
    issue_year = models.PositiveSmallIntegerField()
    face_value = models.CharField(max_length=65)
    currency = models.CharField(max_length=40, blank=True)
    paper_type = models.CharField(blank=True, max_length=65)
    printing_method = MultiSelectField(blank=True, max_length=18, choices=METHOD_CHOICES)
    name = models.CharField(max_length=65)
    series = models.CharField(max_length=65, blank=True)
    color = models.CharField(max_length=40, blank=True)
    watermark = models.CharField(max_length=40, blank=True)
    picture = models.ImageField(upload_to='up_stamps/', blank=True, db_index=True)
    perforation = models.CharField(max_length=40, blank=True)
    def __unicode__(self):
        return u'%i %s' % (self.stamp_id, self.catalogue_name)
class ImQuery(models.Model):
    up_stamp = models.ImageField(upload_to='temp/')
    
class ImList(models.Model):
    filename = models.CharField(max_length=100)
class ImWords(models.Model):
    stamp = models.ForeignKey(Stamp)
    wordid = models.CharField(max_length=100,db_index=True)
    vocname = models.CharField(max_length=100)

class ImHistograms(models.Model):
    stamp = models.ForeignKey(Stamp)
    histogram = models.TextField()
    vocname = models.CharField(max_length=100)


class StampInCatalog(models.Model):
    stamp = models.ForeignKey(Stamp)
    stampcat_id = models.CharField(max_length=15)
    catalog_name = models.CharField(max_length=40)
    trustability = models.CharField(max_length=2, choices=TRUST_CHOICES, default='US')
    class Meta:
        unique_together = ('stampcat_id', 'catalog_name')
        unique_together = ('stamp', 'catalog_name')

class UserProfil(models.Model):
    user = models.OneToOneField(User, primary_key=True)
    location = models.CharField(max_length=30, blank=True)
    avatar = models.ImageField(upload_to='avatars/', blank=True)
    grade = models.PositiveSmallIntegerField(default=0)
    transactions_amount = models.PositiveIntegerField(default=0)
    user_stamps = models.ManyToManyField(Stamp, through='Collection')
    user_contacts = models.ManyToManyField('self', symmetrical=False, through='ContactRelationship')

class ContactRelationship(models.Model):
    user = models.ForeignKey(UserProfil, related_name='from_contact')
    friend = models.ForeignKey(UserProfil, related_name='to_contact')
    type = models.CharField(max_length=2, choices=FRIENDSHIP_CHOICES, default='PE')
    date = models.DateField(auto_now=True)
    class Meta:
        unique_together = ('user', 'friend',)
    
class Collection(models.Model):
    user = models.ForeignKey(UserProfil)
    stamp = models.ForeignKey(Stamp)
    unused_quantity = models.PositiveSmallIntegerField(default=0)
    used_quantity = models.PositiveSmallIntegerField(default=0)
    modification_date = models.DateField(auto_now_add=True)
    deleted = models.BooleanField(default=False)
    class Meta:
        unique_together = ('user', 'stamp',)
    
class Interest(models.Model):
    interested_user = models.ForeignKey(UserProfil)
    collection = models.ForeignKey(Collection)
    quality = models.CharField(max_length=2, choices=QUALITY_CHOICES, default='US')
    state = models.CharField(max_length=2, choices=STATE_CHOICES, default='PE')
    date_creation = models.DateField(auto_now=True)

class Transaction(models.Model):
    interest = models.OneToOneField(Interest, primary_key=True)
    grade_sender = models.PositiveSmallIntegerField(null=True)
    grade_receiver = models.PositiveSmallIntegerField(null=True)
    review_sender = models.TextField(validators=[MaxLengthValidator(450)], blank=True)
    review_receiver = models.TextField(validators=[MaxLengthValidator(450)], blank=True)

class Message(models.Model):
    sender = models.ForeignKey(UserProfil, related_name='sender')
    receiver = models.ForeignKey(UserProfil, related_name='receiver')
    message = models.TextField(validators=[MaxLengthValidator(500)])
    sent_time = models.DateTimeField(auto_now_add=True)
    seen = models.BooleanField(default=False)


def create_user_profil(sender, instance, created, **kwargs):
    if created:
        profil, created = UserProfil.objects.get_or_create(user=instance)

post_save.connect(create_user_profil, sender=User)

src/social website/templates/stamps/display.html
{% extends "base_stamps.html"%}
{%block title%}{{block.super}}{%endblock%}
{%block review%}{%endblock%}
{%block picture%}
    {%if stamp_id.picture.height < stamp_id.picture.width%}
        <img src="{{stamp_id.picture.url}}"alt="Stamp Image" width="250" Height="200"/>
    {%elif stamp_id.picture %}
        <img src="{{stamp_id.picture.url}}"alt="Stamp Image" width="200" Height="250"/>
    {%else%}
        {%load staticfiles%}
        <img src="{%static "nostamp.jpg"%}" alt="Stamp Image" width="200" Height="250"/>
    {%endif%}
{%endblock%}
{%block catalogleft%}
{%endblock%}
{%block catalogright%}
        <fieldset class="commonl">
        <legend>Catalogs</legend>

    {%if catalogs%}
    {%for catalog in catalogs%}
        <p>{{catalog.catalog_name}}: {{catalog.stampcat_id}}</p>
    {%endfor%}
    {%else%}
        <p> No catalog bound to this stamp </p>
    {%endif%}
        </fieldset>
{%endblock%}
{%block common%}
    <p>{{stamp_id.series}} - {{stamp_id.name}}</p>
    <p>{{stamp_id.issue_country}} - {{stamp_id.issue_year}}</p>
    <p>Face value: {{stamp_id.face_value}} {{stamp_id.currency}}</p>
{%endblock%}

{%block advanced%}
    {%if stamp_id.paper_type%}
    <p>Paper type: {{stamp_id.get_paper_type_display}}</p>
    {%endif%}

    {%if stamp_id.printing_method%}
    <p>Printing method: {{stamp_id.get_printing_method_display}}</p>
    {%endif%}

    {%if stamp_id.color%}
    <p>Color: {{stamp_id.color}}</p>
    {%endif%}

    {%if stamp_id.watermark%}
    <p>Watermark: {{stamp_id.watermark}}</p>
    {%endif%}

    {%if stamp_id.secret_mark%}
    <p>Secretmark: {{stamp_id.secret_mark}}</p>
    {%endif%}

{%endblock%}

{%block ownership%}
{% if u.id%}
{{ form.non_field_errors }}
<form action="" method="post">
{% for field in form %}
    <div {% if field.errors %}class="field_error"{%endif%}>
    <p>{{field.label_tag}}:<br/>
    {{field}}</p>
    {% for err in field.errors %}
        <span class="error_message">{{err}}</span>
    {%endfor%}
{%endfor%}
</div>
{% csrf_token %}
<input type="submit" value="Update"/>
</form>
{%endif%}
{%endblock%}

src/social website/templates/stamps/finder.html
{%extends 'base_simple.html'%}
{%block c_fi%}class="active"{%endblock%}

{%block content%}
<div class="row">
<div id="left">
		<fieldset class="commonl">
			<legend>Find a stamp</legend>
<form action="" method="post" enctype="multipart/form-data">
<input type="file" name="s_pic" />
<br />

    {% csrf_token %}
    <button type="submit" value="Submit">Submit</button>
</form>
    {%if q%}
    Uploaded stamp:
    {%endif%}
    {%if q.up_stamp.height < q.up_stamp.width%}
        <img src="{{q.up_stamp.url}}"alt="Stamp Image" width="250" Height="200"/>
    {%elif q.up_stamp %}
        <img src="{{q.up_stamp.url}}"alt="Stamp Image" width="200" Height="250"/>
        {%endif%}
</div>
<div id="right">
{% for item in desc%}
<fieldset class="commonr">
	<legend>{{item.filename}}</legend>
	<div id="avatar">{%if item.picture.height < item.picture.width%}
        <img src="{{item.picture.url}}"alt="Stamp Image" width="250" Height="200"/>
    {%elif item.picture %}
        <img src="{{item.picture.url}}"alt="Stamp Image" width="200" Height="250"/>
        {%endif%}</div><div id="info">
        {{item.series}}:{{item.name}}<br/>
        {{item.issue_country}} - {{item.issue_year}}

        </div>
</fieldset>
{%endfor%}
</div>
</div>
{%endblock%}

src/social website/templates/stamps/list.html
{% extends "base_simple.html"%}
{%block title%}{{block.super}} - Stamps{%endblock%}
{%block c_st%}class="active"{%endblock%}

{%block legend%}Search criteria{%endblock%}
{%block contfieldset %}
    <form action="" method="post">
    Search: <input type="text" name="search"/>
    <select name="criteria">
        <option value="issue_country">Country of issue</option>
        <option value="issue_year">Year of issue</option>
        <option value="color">Color</option>
    </select>
    {%csrf_token%}
    <button type="submit" name="updatesearch" value="ok">Submit</button>
    <input type="hidden" name="hsearch" value="{{sear}}"/>
    <input type="hidden" name="hcriteria" value="{{crit}}"/>
    </form>
</fieldset>
<fieldset class="full">
<legend>Stamps list</legend>
    <table>
    <tr><th>Name</th><th>Series</th><th>Issue Country</th><th>Issue Year</th><th>Face Value</th><th>Catalogs</th></tr>
    {%for stamp, catalog in stamps_list %}
        <tr><td><a href="/stamps/display/?stamp={{stamp.id}}">
            {{stamp.name}}</a></td><td>{{stamp.series}}</td><td>{{stamp.issue_country}}</a></td><td>{{stamp.issue_year}}</td><td>{{stamp.face_value}}</td><td>{%if catalog%}{%for cat in catalog%}{{cat.catalog_name}}: {{cat.stampcat_id}}<br/>{%endfor%}{%else%}--{%endif%}</td></tr>
    {%endfor%}
    </table>
    <br/>
    <span class="pages"><form action="" method="get">
    <button type="submit" name="page" value="{{ p|add:"-1" }}" {% if p == 1 %} disabled="disabled" {%endif%}>Next</button>
    Current : {{p}}
    <button type="submit" name="page" value="{{ p|add:"1" }}" {% if c < 25 %} disabled="disabled" {%endif%}>Previous</button>
    </form></span>
</fieldset>
{%endblock%}

src/social website/templates/stamps/stamp_upload.html
{%extends "base_stamps.html"%}
{%block title%}Upload{%endblock%}
{%block c_up%}class="active"{%endblock%}
{%block form%}
    <form action="" method="post" enctype="multipart/form-data">
{%endblock%}

{%block picture%}
    {%load staticfiles%}
    <img src="{%static "nostamp.jpg"%}" alt="Stamp Image" width="200" Height="250"/>
{%endblock%}

{%block catalog%}
{%load stamps_extras %}
    {%for catform in catalogs %}
        <p>Stamp ID: {{catform.stampcat_id}}<br/>
        Catalog name: {{catform.catalog_name}}</p>
    {%endfor%}
    <button name="add_catalog" value="True">Add catalog</button>
    <button name="del_catalog" value="True">Delete catalog</button>
    <input type="hidden" name="nb_cat" value="{{nb}}"/>
{%endblock%}

{%block nownership%}

{%endblock%}

{%block common%}
    {%for i in stampform%}
        {%if i.name == 'issue_country' or i.name == 'issue_year' or i.name == 'face_value'%}
            {#<div{% if i.errors %}class="field_error"{%endif%}>#}
            {{i.label_tag}}: <br/>
            {{i}}<br/>
            {% for err in i.errors %}
                <span class="error_message">{{err}}</span><br/>
            {%endfor%}
            {#</div>#}
        {%endif%}
    {%endfor%}
{%endblock%}

{%block advanced%}
    {%for i in stampform%}
        {%if i.name != 'issue_country' and i.name != 'issue_year' and i.name != 'face_value'%}
            {#<div{% if i.errors %}class="field_error"{%endif%}>#}
            {{i.label_tag}}:<br/>
            {{i}}<br/>
            {% for err in i.errors %}
                <span class="error_message">{{err}}</span><br/>
            {%endfor%}
            {#</div>#}
        {%endif%}
    {%endfor%}

    {% csrf_token %}
    <button type="submit" value="Submit">Submit</button>
{%endblock%}

{%block closeform%} 
    </form>
{%endblock%}